// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user_service // import "rpc/user/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender" json:"gender,omitempty"`
	Introduction         string   `protobuf:"bytes,4,opt,name=introduction" json:"introduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{0}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfo) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

type BlackInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	TargetId             int64    `protobuf:"varint,2,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	BlackType            int32    `protobuf:"varint,3,opt,name=black_type,json=blackType" json:"black_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlackInfo) Reset()         { *m = BlackInfo{} }
func (m *BlackInfo) String() string { return proto.CompactTextString(m) }
func (*BlackInfo) ProtoMessage()    {}
func (*BlackInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{1}
}
func (m *BlackInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackInfo.Unmarshal(m, b)
}
func (m *BlackInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackInfo.Marshal(b, m, deterministic)
}
func (dst *BlackInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackInfo.Merge(dst, src)
}
func (m *BlackInfo) XXX_Size() int {
	return xxx_messageInfo_BlackInfo.Size(m)
}
func (m *BlackInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlackInfo proto.InternalMessageInfo

func (m *BlackInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *BlackInfo) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *BlackInfo) GetBlackType() int32 {
	if m != nil {
		return m.BlackType
	}
	return 0
}

type CollectionInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	TargetId             int64    `protobuf:"varint,2,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionInfo) Reset()         { *m = CollectionInfo{} }
func (m *CollectionInfo) String() string { return proto.CompactTextString(m) }
func (*CollectionInfo) ProtoMessage()    {}
func (*CollectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{2}
}
func (m *CollectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionInfo.Unmarshal(m, b)
}
func (m *CollectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionInfo.Marshal(b, m, deterministic)
}
func (dst *CollectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionInfo.Merge(dst, src)
}
func (m *CollectionInfo) XXX_Size() int {
	return xxx_messageInfo_CollectionInfo.Size(m)
}
func (m *CollectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionInfo proto.InternalMessageInfo

func (m *CollectionInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CollectionInfo) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

type BrowseInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	ToUid                int64    `protobuf:"varint,2,opt,name=to_uid,json=toUid" json:"to_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrowseInfo) Reset()         { *m = BrowseInfo{} }
func (m *BrowseInfo) String() string { return proto.CompactTextString(m) }
func (*BrowseInfo) ProtoMessage()    {}
func (*BrowseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{3}
}
func (m *BrowseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseInfo.Unmarshal(m, b)
}
func (m *BrowseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseInfo.Marshal(b, m, deterministic)
}
func (dst *BrowseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseInfo.Merge(dst, src)
}
func (m *BrowseInfo) XXX_Size() int {
	return xxx_messageInfo_BrowseInfo.Size(m)
}
func (m *BrowseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseInfo proto.InternalMessageInfo

func (m *BrowseInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *BrowseInfo) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

type UserInfoRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{4}
}
func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(dst, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserInfoResponse struct {
	Userinfo             *UserInfo `protobuf:"bytes,1,opt,name=userinfo" json:"userinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{5}
}
func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (dst *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(dst, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetUserinfo() *UserInfo {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

type UserInfoBatchRequest struct {
	Uids                 []int64  `protobuf:"varint,1,rep,packed,name=uids" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoBatchRequest) Reset()         { *m = UserInfoBatchRequest{} }
func (m *UserInfoBatchRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoBatchRequest) ProtoMessage()    {}
func (*UserInfoBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{6}
}
func (m *UserInfoBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoBatchRequest.Unmarshal(m, b)
}
func (m *UserInfoBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoBatchRequest.Marshal(b, m, deterministic)
}
func (dst *UserInfoBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoBatchRequest.Merge(dst, src)
}
func (m *UserInfoBatchRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoBatchRequest.Size(m)
}
func (m *UserInfoBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoBatchRequest proto.InternalMessageInfo

func (m *UserInfoBatchRequest) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

type UserInfoBatchResponse struct {
	Userinfos            map[int64]*UserInfo `protobuf:"bytes,1,rep,name=userinfos" json:"userinfos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserInfoBatchResponse) Reset()         { *m = UserInfoBatchResponse{} }
func (m *UserInfoBatchResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoBatchResponse) ProtoMessage()    {}
func (*UserInfoBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{7}
}
func (m *UserInfoBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoBatchResponse.Unmarshal(m, b)
}
func (m *UserInfoBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoBatchResponse.Marshal(b, m, deterministic)
}
func (dst *UserInfoBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoBatchResponse.Merge(dst, src)
}
func (m *UserInfoBatchResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoBatchResponse.Size(m)
}
func (m *UserInfoBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoBatchResponse proto.InternalMessageInfo

func (m *UserInfoBatchResponse) GetUserinfos() map[int64]*UserInfo {
	if m != nil {
		return m.Userinfos
	}
	return nil
}

type BlackRequest struct {
	BlackInfo            *BlackInfo `protobuf:"bytes,1,opt,name=black_info,json=blackInfo" json:"black_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlackRequest) Reset()         { *m = BlackRequest{} }
func (m *BlackRequest) String() string { return proto.CompactTextString(m) }
func (*BlackRequest) ProtoMessage()    {}
func (*BlackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{8}
}
func (m *BlackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackRequest.Unmarshal(m, b)
}
func (m *BlackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackRequest.Marshal(b, m, deterministic)
}
func (dst *BlackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackRequest.Merge(dst, src)
}
func (m *BlackRequest) XXX_Size() int {
	return xxx_messageInfo_BlackRequest.Size(m)
}
func (m *BlackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlackRequest proto.InternalMessageInfo

func (m *BlackRequest) GetBlackInfo() *BlackInfo {
	if m != nil {
		return m.BlackInfo
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{9}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type CancelBlackRequest struct {
	BlackInfo            *BlackInfo `protobuf:"bytes,1,opt,name=black_info,json=blackInfo" json:"black_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CancelBlackRequest) Reset()         { *m = CancelBlackRequest{} }
func (m *CancelBlackRequest) String() string { return proto.CompactTextString(m) }
func (*CancelBlackRequest) ProtoMessage()    {}
func (*CancelBlackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{10}
}
func (m *CancelBlackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelBlackRequest.Unmarshal(m, b)
}
func (m *CancelBlackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelBlackRequest.Marshal(b, m, deterministic)
}
func (dst *CancelBlackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelBlackRequest.Merge(dst, src)
}
func (m *CancelBlackRequest) XXX_Size() int {
	return xxx_messageInfo_CancelBlackRequest.Size(m)
}
func (m *CancelBlackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelBlackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelBlackRequest proto.InternalMessageInfo

func (m *CancelBlackRequest) GetBlackInfo() *BlackInfo {
	if m != nil {
		return m.BlackInfo
	}
	return nil
}

type CollectionRequest struct {
	CollectionInfo       *CollectionInfo `protobuf:"bytes,1,opt,name=collection_info,json=collectionInfo" json:"collection_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CollectionRequest) Reset()         { *m = CollectionRequest{} }
func (m *CollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionRequest) ProtoMessage()    {}
func (*CollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{11}
}
func (m *CollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionRequest.Unmarshal(m, b)
}
func (m *CollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionRequest.Marshal(b, m, deterministic)
}
func (dst *CollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionRequest.Merge(dst, src)
}
func (m *CollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionRequest.Size(m)
}
func (m *CollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionRequest proto.InternalMessageInfo

func (m *CollectionRequest) GetCollectionInfo() *CollectionInfo {
	if m != nil {
		return m.CollectionInfo
	}
	return nil
}

type CancelCollectionRequest struct {
	CollectionInfo       *CollectionInfo `protobuf:"bytes,1,opt,name=collection_info,json=collectionInfo" json:"collection_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CancelCollectionRequest) Reset()         { *m = CancelCollectionRequest{} }
func (m *CancelCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CancelCollectionRequest) ProtoMessage()    {}
func (*CancelCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{12}
}
func (m *CancelCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelCollectionRequest.Unmarshal(m, b)
}
func (m *CancelCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelCollectionRequest.Marshal(b, m, deterministic)
}
func (dst *CancelCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelCollectionRequest.Merge(dst, src)
}
func (m *CancelCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CancelCollectionRequest.Size(m)
}
func (m *CancelCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelCollectionRequest proto.InternalMessageInfo

func (m *CancelCollectionRequest) GetCollectionInfo() *CollectionInfo {
	if m != nil {
		return m.CollectionInfo
	}
	return nil
}

type AddBrowseRequest struct {
	BrowseInfo           *BrowseInfo `protobuf:"bytes,1,opt,name=browse_info,json=browseInfo" json:"browse_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddBrowseRequest) Reset()         { *m = AddBrowseRequest{} }
func (m *AddBrowseRequest) String() string { return proto.CompactTextString(m) }
func (*AddBrowseRequest) ProtoMessage()    {}
func (*AddBrowseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{13}
}
func (m *AddBrowseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBrowseRequest.Unmarshal(m, b)
}
func (m *AddBrowseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBrowseRequest.Marshal(b, m, deterministic)
}
func (dst *AddBrowseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBrowseRequest.Merge(dst, src)
}
func (m *AddBrowseRequest) XXX_Size() int {
	return xxx_messageInfo_AddBrowseRequest.Size(m)
}
func (m *AddBrowseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBrowseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBrowseRequest proto.InternalMessageInfo

func (m *AddBrowseRequest) GetBrowseInfo() *BrowseInfo {
	if m != nil {
		return m.BrowseInfo
	}
	return nil
}

type CreateUserRequest struct {
	Userinfo             *UserInfo `protobuf:"bytes,1,opt,name=userinfo" json:"userinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{14}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserinfo() *UserInfo {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

type BlackListRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	BlackType            int32    `protobuf:"varint,2,opt,name=black_type,json=blackType" json:"black_type,omitempty"`
	LastID               int64    `protobuf:"varint,3,opt,name=lastID" json:"lastID,omitempty"`
	Offset               int64    `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlackListRequest) Reset()         { *m = BlackListRequest{} }
func (m *BlackListRequest) String() string { return proto.CompactTextString(m) }
func (*BlackListRequest) ProtoMessage()    {}
func (*BlackListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{15}
}
func (m *BlackListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackListRequest.Unmarshal(m, b)
}
func (m *BlackListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackListRequest.Marshal(b, m, deterministic)
}
func (dst *BlackListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackListRequest.Merge(dst, src)
}
func (m *BlackListRequest) XXX_Size() int {
	return xxx_messageInfo_BlackListRequest.Size(m)
}
func (m *BlackListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlackListRequest proto.InternalMessageInfo

func (m *BlackListRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *BlackListRequest) GetBlackType() int32 {
	if m != nil {
		return m.BlackType
	}
	return 0
}

func (m *BlackListRequest) GetLastID() int64 {
	if m != nil {
		return m.LastID
	}
	return 0
}

func (m *BlackListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type FeedListRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	LastID               int64    `protobuf:"varint,2,opt,name=lastID" json:"lastID,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedListRequest) Reset()         { *m = FeedListRequest{} }
func (m *FeedListRequest) String() string { return proto.CompactTextString(m) }
func (*FeedListRequest) ProtoMessage()    {}
func (*FeedListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{16}
}
func (m *FeedListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedListRequest.Unmarshal(m, b)
}
func (m *FeedListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedListRequest.Marshal(b, m, deterministic)
}
func (dst *FeedListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedListRequest.Merge(dst, src)
}
func (m *FeedListRequest) XXX_Size() int {
	return xxx_messageInfo_FeedListRequest.Size(m)
}
func (m *FeedListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedListRequest proto.InternalMessageInfo

func (m *FeedListRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *FeedListRequest) GetLastID() int64 {
	if m != nil {
		return m.LastID
	}
	return 0
}

func (m *FeedListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type FeedListResponse struct {
	TargetIds            []int64  `protobuf:"varint,1,rep,packed,name=target_ids,json=targetIds" json:"target_ids,omitempty"`
	HasMore              bool     `protobuf:"varint,2,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedListResponse) Reset()         { *m = FeedListResponse{} }
func (m *FeedListResponse) String() string { return proto.CompactTextString(m) }
func (*FeedListResponse) ProtoMessage()    {}
func (*FeedListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_70d25a137944f7a4, []int{17}
}
func (m *FeedListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedListResponse.Unmarshal(m, b)
}
func (m *FeedListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedListResponse.Marshal(b, m, deterministic)
}
func (dst *FeedListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedListResponse.Merge(dst, src)
}
func (m *FeedListResponse) XXX_Size() int {
	return xxx_messageInfo_FeedListResponse.Size(m)
}
func (m *FeedListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedListResponse proto.InternalMessageInfo

func (m *FeedListResponse) GetTargetIds() []int64 {
	if m != nil {
		return m.TargetIds
	}
	return nil
}

func (m *FeedListResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*BlackInfo)(nil), "user.BlackInfo")
	proto.RegisterType((*CollectionInfo)(nil), "user.CollectionInfo")
	proto.RegisterType((*BrowseInfo)(nil), "user.BrowseInfo")
	proto.RegisterType((*UserInfoRequest)(nil), "user.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "user.UserInfoResponse")
	proto.RegisterType((*UserInfoBatchRequest)(nil), "user.UserInfoBatchRequest")
	proto.RegisterType((*UserInfoBatchResponse)(nil), "user.UserInfoBatchResponse")
	proto.RegisterMapType((map[int64]*UserInfo)(nil), "user.UserInfoBatchResponse.UserinfosEntry")
	proto.RegisterType((*BlackRequest)(nil), "user.BlackRequest")
	proto.RegisterType((*EmptyResponse)(nil), "user.EmptyResponse")
	proto.RegisterType((*CancelBlackRequest)(nil), "user.CancelBlackRequest")
	proto.RegisterType((*CollectionRequest)(nil), "user.CollectionRequest")
	proto.RegisterType((*CancelCollectionRequest)(nil), "user.CancelCollectionRequest")
	proto.RegisterType((*AddBrowseRequest)(nil), "user.AddBrowseRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*BlackListRequest)(nil), "user.BlackListRequest")
	proto.RegisterType((*FeedListRequest)(nil), "user.FeedListRequest")
	proto.RegisterType((*FeedListResponse)(nil), "user.FeedListResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_user_70d25a137944f7a4) }

var fileDescriptor_user_70d25a137944f7a4 = []byte{
	// 757 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x4f, 0x1a, 0x4d,
	0x14, 0x0e, 0xac, 0xf8, 0xc2, 0xc1, 0x17, 0xd6, 0x79, 0x45, 0x79, 0x31, 0x26, 0x64, 0xda, 0x0b,
	0xe2, 0x85, 0x6d, 0x6d, 0x9a, 0x18, 0xdb, 0x6a, 0xc4, 0xef, 0xd4, 0xde, 0xac, 0x35, 0x69, 0x7b,
	0x43, 0x96, 0xdd, 0x83, 0x6e, 0xc0, 0x1d, 0x3a, 0x33, 0xd8, 0xf0, 0xab, 0xfa, 0x37, 0xfa, 0xb3,
	0x9a, 0x9d, 0xd9, 0x59, 0xd8, 0x45, 0x8c, 0xb6, 0xbd, 0xd1, 0x99, 0xb3, 0xf3, 0x3c, 0xe7, 0xf3,
	0x39, 0x01, 0x6a, 0x43, 0xce, 0x24, 0x7b, 0x31, 0x12, 0xc8, 0xd5, 0x9f, 0x2d, 0x75, 0x27, 0x0b,
	0xd1, 0x99, 0x4a, 0x28, 0x5e, 0x09, 0xe4, 0xe7, 0x61, 0x8f, 0x11, 0x1b, 0xac, 0x51, 0xe0, 0xd7,
	0x73, 0xcd, 0x5c, 0xcb, 0x72, 0xa2, 0x23, 0x69, 0x40, 0x31, 0x0c, 0xbc, 0x7e, 0xe8, 0xde, 0x62,
	0x3d, 0xdf, 0xcc, 0xb5, 0x4a, 0x4e, 0x72, 0x27, 0xab, 0xb0, 0x78, 0x8d, 0xa1, 0x8f, 0xbc, 0x6e,
	0x35, 0x73, 0xad, 0x82, 0x13, 0xdf, 0x08, 0x85, 0xa5, 0x20, 0x94, 0x9c, 0xf9, 0x23, 0x4f, 0x06,
	0x2c, 0xac, 0x2f, 0x28, 0x5c, 0xca, 0x46, 0xbf, 0x40, 0xa9, 0x3d, 0x70, 0xbd, 0xfe, 0x1c, 0xb7,
	0xeb, 0x50, 0x92, 0x2e, 0xbf, 0x46, 0xd9, 0x09, 0x7c, 0xe5, 0xd7, 0x72, 0x8a, 0xda, 0x70, 0xee,
	0x93, 0x0d, 0x80, 0x6e, 0x84, 0xed, 0xc8, 0xf1, 0x10, 0x63, 0xdf, 0x25, 0x65, 0xf9, 0x34, 0x1e,
	0x22, 0xdd, 0x87, 0xca, 0x21, 0x1b, 0x0c, 0x50, 0x39, 0xfa, 0x0d, 0x7e, 0xfa, 0x06, 0xa0, 0xcd,
	0xd9, 0x77, 0x81, 0x73, 0xc0, 0x35, 0x58, 0x94, 0xac, 0x33, 0x4a, 0x90, 0x05, 0xc9, 0xae, 0x02,
	0x9f, 0x3e, 0x83, 0xaa, 0x29, 0xa4, 0x83, 0xdf, 0x46, 0x28, 0xe4, 0x2c, 0x96, 0xee, 0x81, 0x3d,
	0x79, 0x24, 0x86, 0x2c, 0x14, 0x48, 0x36, 0xa1, 0x18, 0x75, 0x22, 0x08, 0x7b, 0x4c, 0x3d, 0x2d,
	0x6f, 0x57, 0xb6, 0x54, 0x9b, 0x92, 0x97, 0xc9, 0x77, 0xba, 0x09, 0x2b, 0xc6, 0xda, 0x76, 0xa5,
	0x77, 0x63, 0x3c, 0x11, 0x58, 0x18, 0x05, 0xbe, 0xa8, 0xe7, 0x9a, 0x56, 0xcb, 0x72, 0xd4, 0x99,
	0xfe, 0xc8, 0x41, 0x2d, 0xf3, 0x38, 0xf6, 0x78, 0x06, 0x25, 0xc3, 0xa8, 0x21, 0xe5, 0xed, 0xcd,
	0xb4, 0xcb, 0xd4, 0x7b, 0x65, 0x55, 0x8f, 0x8f, 0x43, 0xc9, 0xc7, 0xce, 0x04, 0xdc, 0xb8, 0x80,
	0x4a, 0xfa, 0x63, 0x94, 0x73, 0x1f, 0xc7, 0x26, 0xe7, 0x3e, 0x8e, 0xc9, 0x73, 0x28, 0xdc, 0xb9,
	0x83, 0x91, 0x1e, 0xa0, 0xd9, 0xe4, 0xf4, 0xc7, 0xdd, 0xfc, 0x4e, 0x8e, 0xee, 0xc1, 0x92, 0x9a,
	0x0a, 0x93, 0xd5, 0x96, 0xe9, 0xf4, 0x54, 0x6d, 0xaa, 0x1a, 0x9e, 0x4c, 0x4f, 0xdc, 0xfa, 0xe8,
	0x48, 0xab, 0xf0, 0xef, 0xf1, 0xed, 0x50, 0x8e, 0x4d, 0xe0, 0xf4, 0x08, 0xc8, 0xa1, 0x1b, 0x7a,
	0x38, 0xf8, 0x23, 0x5a, 0x07, 0x96, 0x27, 0x13, 0x65, 0x48, 0xde, 0x43, 0xd5, 0x4b, 0x8c, 0xd3,
	0x4c, 0x2b, 0x9a, 0x29, 0x3d, 0x83, 0x4e, 0xc5, 0x4b, 0xdd, 0xe9, 0x67, 0x58, 0xd3, 0x91, 0xfd,
	0x75, 0xe6, 0x63, 0xb0, 0x0f, 0x7c, 0x5f, 0x4f, 0xb0, 0xa1, 0x7c, 0x05, 0xe5, 0xae, 0x32, 0x4c,
	0xd3, 0xd9, 0x71, 0xca, 0xc9, 0xac, 0x3b, 0xd0, 0x4d, 0xce, 0x74, 0x1f, 0x96, 0x0f, 0x39, 0xba,
	0x12, 0xa3, 0x46, 0x19, 0x9e, 0xa7, 0x8c, 0xaa, 0x00, 0x5b, 0x55, 0xf3, 0x22, 0x10, 0x72, 0xae,
	0x20, 0x32, 0x62, 0xce, 0x67, 0xc4, 0x1c, 0xed, 0x98, 0x81, 0x2b, 0xe4, 0xf9, 0x91, 0xd2, 0xb9,
	0xe5, 0xc4, 0xb7, 0xc8, 0xce, 0x7a, 0x3d, 0x81, 0x52, 0x6d, 0x17, 0xcb, 0x89, 0x6f, 0xf4, 0x12,
	0xaa, 0x27, 0x88, 0xfe, 0xc3, 0x3e, 0x27, 0xa4, 0xf9, 0x39, 0xa4, 0x56, 0x8a, 0xf4, 0x02, 0xec,
	0x09, 0x69, 0x2c, 0xa1, 0x0d, 0x80, 0x64, 0x83, 0x18, 0xd9, 0x95, 0xcc, 0x0a, 0x11, 0xe4, 0x7f,
	0x28, 0xde, 0xb8, 0xa2, 0x73, 0xcb, 0xb8, 0x4e, 0xaa, 0xe8, 0xfc, 0x73, 0xe3, 0x8a, 0x8f, 0x8c,
	0xe3, 0xf6, 0xcf, 0x02, 0x40, 0x54, 0xae, 0x4b, 0xe4, 0x77, 0xc8, 0xc9, 0x3b, 0x28, 0x9f, 0xa2,
	0x34, 0x22, 0x22, 0xb5, 0x4c, 0x3d, 0x75, 0x12, 0x8d, 0xd5, 0xac, 0x39, 0x0e, 0xe3, 0x03, 0xd8,
	0xa7, 0x28, 0x95, 0x5a, 0x13, 0x8a, 0xc6, 0xbd, 0x52, 0xd6, 0x3c, 0xeb, 0x0f, 0xc8, 0x9c, 0x1c,
	0x28, 0xb2, 0xb3, 0x40, 0x48, 0xc6, 0xc7, 0x7a, 0x2c, 0x4c, 0x3c, 0x99, 0xa2, 0x9a, 0x78, 0x66,
	0xca, 0xb2, 0x07, 0x4b, 0x51, 0x3c, 0xa6, 0xef, 0x64, 0x75, 0x4a, 0x56, 0x8f, 0xc1, 0xb7, 0x61,
	0xf9, 0x14, 0xe5, 0x64, 0xc2, 0x15, 0xc9, 0x13, 0x63, 0x78, 0x09, 0x05, 0xe5, 0x8f, 0x90, 0x29,
	0xe7, 0x06, 0xf4, 0x9f, 0xb6, 0xa5, 0xd6, 0x44, 0xd4, 0x83, 0xa9, 0x35, 0x41, 0xea, 0xb1, 0xce,
	0x66, 0x36, 0xc7, 0xfd, 0xe8, 0x5d, 0x80, 0x49, 0xc0, 0x64, 0x2d, 0x2b, 0xd2, 0x07, 0xb1, 0x27,
	0x60, 0x67, 0xd7, 0x00, 0xd9, 0x98, 0x76, 0xff, 0x48, 0x9e, 0x1d, 0x28, 0x25, 0xa2, 0x37, 0x45,
	0xcf, 0x6e, 0x81, 0xf9, 0xd1, 0x27, 0x3a, 0x4f, 0xa2, 0xcf, 0x2a, 0xff, 0x5e, 0x6c, 0xbb, 0xf1,
	0xb5, 0xce, 0x87, 0x9e, 0xfe, 0x61, 0x31, 0xec, 0xbe, 0x8d, 0xfe, 0x77, 0x04, 0xf2, 0xbb, 0xc0,
	0xc3, 0xee, 0xa2, 0xfa, 0x91, 0xf1, 0xfa, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0x91, 0x3f,
	0x88, 0x7d, 0x08, 0x00, 0x00,
}
